# Generated by Django 3.1.3 on 2021-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='valid',
            field=models.IntegerField(),
        ),
    ]
